### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by losh11** [litecoin-association/LitecoinNode#16]
######glob-vars.sh - random characters generation leads to ‘permission denied’
>                       /dev/urandom is in accessible

######NOT JUST FOR DEBIAN 
* add in the final comment (print) giving the users IP address. I think it’s kinda useful for the end user to have a print out of the IP, since not everyone has a domain. This is pretty hard to do, usually done with a curl to one of those websites which runs a python script. I’ll try to add it in.

###### Shutdown failed - look at this:
> All done! Do you want to reboot? (Y/N) y

> Shutdown scheduled for Thu 2015-08-06 01:29:25 CEST, use 'shutdown -c' to cancel.
> root@mango:~# 
> Broadcast message from root@mango (Thu 2015-08-06 01:28:25 CEST):

> Press CTRL+C to abort.
> The system is going down for reboot at Thu 2015-08-06 01:29:25 CEST!

> Write failed: Broken pipe
> Loshans-MacBook-Pro:~ Loshan$ ssh root@mango.litecoinnode.org
> ssh: connect to host mango.litecoinnode.org port 22: No route to host

Not sure if this was caused by us? Was it? Can’t login anymore. It seems like the server is offline, seeing that the HTML page is down. Could you restart the machine again?

**Comment by LitecoinNode** [comment]
mango.litecoinnode.org is up and running again.

**Comment by losh11** [comment]
Do you know why it went down?
I didn't change any ufw settings, so ssh ports should stay up...
It only happened when I tried to reboot.

**Comment by LitecoinNode** [comment]
It hang in the shutdown cycle and did not come back up.
