### ISSUE TITLE
Porting to another digital currency?

### ISSUE THREAD

**Issue by gotchay** [litecoin-association/LitecoinNode#18]
How difficult would it be to change the script to run a node status page for another currency, say Bitcoin? Vertcoin?

**Comment by losh11** [comment]
No very, probably would take under a day.

It's not like there is anything hard, it's just that you have to run a lot of tests to make this work. 
Other coins can use different amount of ram, bandwidth and so on... And when this changes, some of the global functions also have to change. The maximum number of peers is calculated using RAM left, and Mike and I found that what we chose was 'just right' for Litecoin.

Pretty much everything else would be to:-
* create a link to a new blockchain file for your coin
* create a link to your QT/Core wallet
* find a list of supernodes and change the array for random nodes
* modify all directories that have the name Litecoin or litecoind to what ever your coin uses
* change all references to Litecoin.
* do tests to find the perfect values for your network.
