### ISSUE TITLE
Public/Press release

### ISSUE THREAD

**Issue by losh11** [litecoin-association/LitecoinNode#19]
Hey, LA Directors, can someone make a public announcement for the LitecoinNode project.

Basic points that can be mentioned are all in the features sections in the README file.
Supports Ubuntu-like Linux distributions, Debian-like distros.
Practically everything will be set up for the user.
Most of the work is done by Mike (if you want to make yourself known Mike, please announce yourself below).

All install instructions are in the README file.
Whoever is going to write up the press release, please just read the README file. It is designed to be very clear and easy to understand.

**Comment by newb1** [comment]
And zero response... lovely.

**Comment by losh11** [comment]
@newb1 This project is actually useful to lots of people. This isn't just some simple script which runs once and ends, Mike (did 99% of the work) and a lot or time was put into this project.

**Comment by newb1** [comment]
I have no doubt about its usefulness. I am distressed that there has been
no response from my colleagues. I am also distressed about the state of my
inbox. I need to get this shit cleaned up. I get a lot of unnecessary junk
(e.g. LitecoinTalk crap and other auto forwards from various crypto
communities). This junk makes it difficult for me to see the important
items.

**Comment by TheRealMage** [comment]
@losh11 @newb1 Please send me an email to remind me to do this, and losh some quick basic points for me to write something around would be nice. Thanks

**Comment by losh11** [comment]
@TheRealMage will do once I've gotten home.

Please remind me to make a pull request for Hive-iOS. Might forget!
